language: php
php:
  - 7.1
  - nightly
install:
  - composer install
  - npm install
before_script:
  - mysql -e 'SET GLOBAL innodb_file_format = Barracuda;'
  - mysql -e 'SET GLOBAL innodb_large_prefix = ON;'
  - mysql -e 'CREATE DATABASE `forge`;'
  - ln -s .env.travis .env
script:
  - npm run build
  - composer travis-test
after_script:
  - composer coveralls
