language: php
php:
  - 7.1
  - 7.2
  - nightly
install:
  - composer install
  - npm install
after_install:
  - npm run build
before_script:
  - mysql -e 'SET GLOBAL innodb_file_format = Barracuda;'
  - mysql -e 'SET GLOBAL innodb_file_format_max = Barracuda;'
  - mysql -e 'SET GLOBAL innodb_large_prefix = ON;'
  - mysql -e 'CREATE DATABASE `forge`;'
  - cp .env.travis .env
script:
  - composer test
after_script:
  - composer coveralls
